name: latest_api_feature_pipeline

on:
  workflow_dispatch:
#  schedule:
#    - cron: '*/10 * * * *'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.5'
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: make script executable
        run: chmod +x scripts/run_feature_pipeline.sh

      - name: execute python workflows from bash script
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
          API_PASSWORD: ${{ secrets.API_PASSWORD }}
          API_USERNAME: ${{ secrets.API_USERNAME }}
        run: ./scripts/run_feature_pipeline.sh
